### ISSUE TITLE
GB Postal Codes

### ISSUE THREAD

**Issue by phobos1** [coderholic/django-cities#163]
Full postal codes for United Kingdom(GB) locate in http://download.geonames.org/export/zip/GB_full.csv.zip, therefore valid postal codes for GB not importing with `manage.py cities` command

**Comment by blag** [comment]
I'm immediately closing this issue without looking at it because it doesn't contain the information I asked for in the issue template I created for this repo. Feel free to reopen this issue once you have filled out the issue template at:

https://github.com/coderholic/django-cities/blob/master/ISSUE_TEMPLATE.md

by copying that, pasting it into your issue form:

![issue_template](https://cloud.githubusercontent.com/assets/597113/24258849/9e9b02e4-0fb4-11e7-8c8f-3ac5a8111947.png)

and filling out all of the necessary information:

![issue_template_2](https://cloud.githubusercontent.com/assets/597113/24258857/a2346490-0fb4-11e7-825d-177699ac0cb2.png)

Once you have done that I will take a look at this issue. Thanks!

(These pictures are just examples from a different repository but the process is the same.)

**Comment by blag** [comment]
Check out issue #162 for a mostly acceptable example.
