### ISSUE TITLE
Differences between Github and PyPi versions

### ISSUE THREAD

**Issue by Alexgmin** [coderholic/django-cities#192]
On PyPi the latest version is 0.5.0.5, yet here is the 0.5.0.4. Why?

Also, I can't find a changelog that's not outdated, Is there one?

**Comment by blag** [comment]
I pushed the code from `v0.5.0.5` to the `v0.5.0.5` branch, feel free to check it out and test it.

No, I do not keep a changelog. You should be able to check out the git log though. I will try to add the version number to the commit messages though (eg: "Update to v0.5.0.5" instead of "Bump version for PyPI release").

I'm happy to answer any more questions you have. And I'll keep this issue open as long as you have questions and close it after about a week of inactivity.

**Comment by blag** [comment]
Closing, but if you have more questions feel free to ask them here (even if it's closed).
